name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome, thank you for supporting echarts-for-angular and helping to enhance it.'
        pr-message: 'Thank you so much for your work in moving this project forward.'
